---
- hosts: all
  gather_facts: no
  vars_files:
    - group_vars/values.yaml
  pre_tasks:
    - include_tasks: tasks/push_ssh_key.yml

- hosts: all
  vars_files:
    - group_vars/values.yaml
  vars:
    ansible_host_key_checking: false
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    ansible_become: yes
    ansible_ssh_user: ubuntu
  pre_tasks:
    - name: Set GitHub Facts
      set_fact:
        git_repo: "{{ git.url.split('/')[4] }}"
        git_owner: "{{ git.url.split('/')[3] }}"
    - include_tasks: tasks/cleanup.yml
    - import_role:
        name: common
    - include_tasks: tasks/push_ssh_key.yml
    - name: 'Remove all crontab entries'
      with_items: "{{ cron_entries }}"
      ansible.builtin.cron:
        name: "{{ item.name }}"
        state: absent
