---
- hosts: all
  gather_facts: no
  vars_files:
    - group_vars/values.yaml
  tasks:
    - include_tasks: tasks/push_ssh_key.yml

- hosts: all
  vars_files:
    - group_vars/values.yaml
  vars:
    ansible_host_key_checking: false
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    ansible_become: yes
    ansible_ssh_user: ubuntu
  pre_tasks:
    - name: Set GitHub Facts
      set_fact:
        git_repo: "{{ git.url.split('/')[4] }}"
        git_owner: "{{ git.url.split('/')[3] }}"
    - include_tasks: tasks/cleanup.yml
    - import_role:
        name: common
    - include_tasks: tasks/push_ssh_key.yml
    - import_role:
        name: td-agent
    - include_tasks: tasks/push_ssh_key.yml
    - import_role:
        name: prom-metrics
    - include_tasks: tasks/push_ssh_key.yml
  roles:
    - app

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Apply service monitor
      community.kubernetes.k8s:
        state: present
        src: /tmp/service-monitor.yaml
        apply: yes
    - name: Remove service-monitor.yaml
      ansible.builtin.file:
        path: /tmp/service-monitor.yaml
        state: absent