---
- name: Kill running single jobs
  with_items: "{{ single_runs }}"
  shell: "pkill -f {{ item.name }}.sh"
  ignore_errors: True
  when: single_runs is defined

- name: Kill running cron jobs
  with_items: "{{ cron_entries }}"
  shell: "pkill -f {{ item.name }}.sh"
  ignore_errors: True
  when: cron_entries is defined

- name: Kill running services
  with_items: "{{ service_entries }}"
  ansible.builtin.systemd:
    name: "{{ item.name }}"
    state: stopped
  ignore_errors: True
  when: service_entries is defined

- name: Kill running backups
  with_items: "{{ backups }}"
  ansible.builtin.systemd:
    name: "{{ item.name }}-backup"
    state: stopped
  ignore_errors: True
  when: backups is defined

- name: Remove Virtual Env folder
  file:
    path: "/home/{{ instance_user }}/{{ clone_dir }}/{{ python.env_name }}"
    state: absent
