---
- name: Create a directory if it does not exist
  become_user: "{{ instance_user }}"
  ansible.builtin.file:
    path: "/home/{{ instance_user }}/runs"
    state: directory
    mode: "0755"

- name: "Create single entrypoint for {{ item.name }}"
  become_user: "{{ instance_user }}"
  vars:
    type: runs
    entrypoint: "{{ item.entrypoint }}"
    name: "{{ item.name }}"
  ansible.builtin.template:
    src: entrypoint.sh
    dest: "/home/{{ instance_user }}/runs/{{ item.name }}.sh"
    mode: "0755"

- name: "Single Run for {{ item.name }}"
  become_user: "{{ instance_user }}"
  shell: "/home/{{ instance_user }}/runs/{{ item.name }}.sh"

- name: "Cleanup Run for {{ item.name }}"
  become_user: "{{ instance_user }}"
  file:
    path: "/home/{{ instance_user }}/runs/{{ item.name }}.sh"
    state: absent
