---
- name: Check is conda installed
  shell: command -v conda >/dev/null 2>&1
  register: is_conda_exist
  ignore_errors: yes

- name: Output of is_conda_exist
  debug:
    msg: "{{ is_conda_exist }}"

- name: Install Conda
  when: is_conda_exist.stdout[0] is undefined
  block:
    - include_tasks: tasks/push_ssh_key.yml
    - name: Download Conda
      get_url:
        url: https://repo.anaconda.com/archive/Anaconda3-2020.11-Linux-x86_64.sh
        dest: /tmp/install-conda.sh
        mode: 0550

    - name: Create conda folder
      become: True
      file:
        path: /opt/conda3
        state: directory
        owner: ubuntu
        mode: 755
        recurse: yes

    - name: Run the installer
      shell: /tmp/install-conda.sh -b -u -p /opt/conda3

    - name: Remove the installer
      file:
        state: absent
        path: /tmp/install-conda.sh

    - name: Add conda bin to environment.d
      become: True
      shell: echo "PATH=\"/opt/conda3/bin:$PATH\"" > /etc/environment

    - name: conda - read permission for all
      become: True
      file:
        path: /opt/conda3
        mode: +r
        recurse: yes

    - name: conda - execution permission for all
      become: True
      file:
        path: /opt/conda3/bin
        mode: +x
        recurse: yes
    - include_tasks: tasks/push_ssh_key.yml
